spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petalscrm
    username: abhilash
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Disabling Hibernate's automatic DDL generation
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000
